import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";
import ThemeProvider from "./lib/utils/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#ededed] text-[#171717] dark:bg-[#0a0a0a] dark:text-[#ededed] antialiased`}
      >
        <Script 
          strategy="afterInteractive"
          src={`https://www.google.com/recaptcha/api.js?render=${process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY!}`} 
        />
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
